apiVersion: v1
kind: ConfigMap
metadata:
  name: fuseki-config
  namespace: default
data:
  config.ttl: |
    ## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

    PREFIX :        <#>
    PREFIX fuseki:  <http://jena.apache.org/fuseki#>
    PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX ja:      <http://jena.hpl.hp.com/2005/11/Assembler#>
    PREFIX tdb2:    <http://jena.apache.org/2016/tdb#>

    [] rdf:type fuseki:Server ;
      fuseki:services (
        :prod_service
      ) .

    :prod_service rdf:type fuseki:Service ;
        fuseki:name "ds" ;
        fuseki:endpoint [
            fuseki:operation fuseki:query ; 
            fuseki:name "sparql"
        ] ;
        fuseki:endpoint [ 
            # SPARQL query service (alt name)
            fuseki:operation fuseki:query ; 
            fuseki:name "query" 
        ] ;

        fuseki:endpoint [ 
            # SPARQL update service
            fuseki:operation fuseki:update ; 
            fuseki:name "update" 
        ] ;

        fuseki:endpoint [ 
            # HTML file upload service
            fuseki:operation fuseki:upload ; 
            fuseki:name "upload" 
        ] ;

        fuseki:endpoint [ 
            # SPARQL Graph Store Protocol (read)
            fuseki:operation fuseki:gsp_r ; 
            fuseki:name "get" 
        ] ;
        fuseki:endpoint [ 
            # SPARQL Graph Store Protcol (read and write)
            fuseki:operation fuseki:gsp_rw ; 
            fuseki:name "data" 
        ] ;

      fuseki:dataset :prod_dataset_tdb2 ;

        .

    :prod_dataset_tdb2 rdf:type  tdb2:DatasetTDB2 ;
        tdb2:location "/fuseki/databases/prod" ;
        rdfs:label "prod";
        fuseki:name "prod";
    .
    
  shiro.ini: |
    #   contributor license agreements.  See the NOTICE file distributed with
    #   this work for additional information regarding copyright ownership.
    #   The ASF licenses this file to You under the Apache License, Version 2.0
    #   (the "License"); you may not use this file except in compliance with
    #   the License.  You may obtain a copy of the License at
    #
    #       http://www.apache.org/licenses/LICENSE-2.0
    #
    #   Unless required by applicable law or agreed to in writing, software
    #   distributed under the License is distributed on an "AS IS" BASIS,
    #   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    #   See the License for the specific language governing permissions and
    #   limitations under the License.

    [main]
    # Development
    ssl.enabled = false

    plainMatcher=org.apache.shiro.authc.credential.SimpleCredentialsMatcher
    #iniRealm=org.apache.shiro.realm.text.IniRealm
    iniRealm.credentialsMatcher = $plainMatcher

    #localhost=org.apache.jena.fuseki.authz.LocalhostFilter

    [users]
    # Implicitly adds "iniRealm =  org.apache.shiro.realm.text.IniRealm"
    # The admin password will be replaced by value of ADMIN_PASSWORD
    # variable by docker-entrypoint.sh on FIRST start up.
    admin={{ .Values.fuseki.adminPassword }}

    [roles]

    [urls]
    ## Control functions open to anyone
    # /$/status = anon
    # /$/ping   = anon

    ## and the rest are restricted
    # /$/** = authcBasic,user[admin]

    ## Sparql update is restricted
    # /*/update/** = authcBasic,user[admin]
    # /*/sparql/** = authcBasic,user[admin]
    # /*/upload/** = authcBasic,user[admin]
    # /*/query/** = authcBasic,user[admin]
    # /*/get/** = authcBasic,user[admin]
    # /*/data/** = authcBasic,user[admin]
    # 
    # ## GSP update is restricted


    ## If you want simple, basic authentication user/password
    ## on the operations,
    ##    1 - set a password in [users]
    ##    2 - change the line above to:
    ## /$/** = authcBasic,user[admin]
    ## and set a better

    ## or to allow any access.
    # /$/** = anon

    # Everything else
    /**=anon