{{- if .Values.nextcloud.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bsw.fullname" . }}-nextcloud
  labels:
    {{- include "bsw.labels" . | nindent 4 }}
    app: nextcloud
spec:
  type: {{ .Values.nextcloud.service.type }}
  ports:
    - port: {{ .Values.nextcloud.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nextcloud
{{- end }}