version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-dev
    command: start-dev --http-port=8081 --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_FEATURES: preview
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: ""
    ports:
      - "8082:8081"
    volumes:
      - ./realms:/opt/keycloak/data/import
    restart: unless-stopped
